# Generated by Django 4.2.7 on 2024-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Banner rasmlari', 'verbose_name_plural': 'Banner rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo lar'},
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='banner_image/', verbose_name='banner rasmi'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='logo'),
        ),
    ]
