# Generated by Django 4.2.7 on 2024-11-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutachievements_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_full_name',
            field=models.CharField(max_length=255, verbose_name="O'qituvchi ism familiyasi"),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ariza holati'),
        ),
    ]
