# Generated by Django 4.2.7 on 2024-10-30 15:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutowner',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
